version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www
    ports:
      - 8080:9000
    links:
      - database
      - rabbitmq
      - redis

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./docker/database/data:/var/lib/database

  rabbitmq:
    image: rabbitmq:management
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
